# Generated by Django 3.1.2 on 2020-10-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WxStats',
            fields=[
                ('month_day', models.TextField(help_text='month and day', max_length=5, primary_key=True, serialize=False)),
                ('last_date', models.DateField()),
                ('record_min_temp', models.FloatField()),
                ('avg_min_temp', models.FloatField()),
                ('avg_max_temp', models.FloatField()),
                ('record_max_temp', models.FloatField()),
                ('stats_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentWx',
            fields=[
                ('date', models.DateField(help_text='month and day', primary_key=True, serialize=False)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('max_temp', models.FloatField(blank=True, null=True)),
                ('month_day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weather.wxstats', unique=True)),
            ],
        ),
    ]
