# Generated by Django 3.1.2 on 2020-10-27 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentwx',
            name='month_day',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='weather.wxstats'),
        ),
    ]
